export function installReaderApi(runtime) {
  const canCreateStore = runtime.KP && typeof runtime.KP.createStore === "function";
  const kakaoStore = runtime.state.kakaoStore || (canCreateStore ? runtime.KP.createStore() : null);
  if (!kakaoStore) throw new Error("Kakao canonical Store is unavailable");
  runtime.state.kakaoStore = kakaoStore;
  const kakaoRetryScheduler = runtime.KP.createRetryScheduler({
    store: kakaoStore,
    setTimer: (callback, delay) => window.setTimeout(callback, delay),
    clearTimer: timer => window.clearTimeout(timer),
    isPlaceholder: target => target instanceof HTMLImageElement && runtime.isDataUrl(runtime.resolveImageUrl(target)),
    isTargetUsable: target => !!target && target.isConnected && !runtime.state.invalidated,
    isTargetReady: target => target instanceof HTMLImageElement && target.complete && runtime.passesTargetFilter(target, true),
    onReady: runtime.queuePageAutoTranslate
  });
  runtime.kakaoRetryScheduler = kakaoRetryScheduler;
  const kakaoCanonicalPipeline = runtime.KP && runtime.KR && typeof runtime.KP.createCanonicalPipeline === "function" ? runtime.KP.createCanonicalPipeline({
    store: kakaoStore,
    reconciler: runtime.KR,
    extractTargetPayload: (target, scopedKey) => runtime.extractTargetPayload(target, runtime.buildKakaoCanonicalPayloadCacheKey(scopedKey, target), {
      skipKakaoStitch: true
    }),
    buildPageIdentity: runtime.buildKakaoPageIdentity,
    commitPageIdentity: (target, identity) => runtime.bindKakaoTargetToPage(target, identity && identity.pageId, identity && identity.imageRevision),
    notifyCanonicalPageReady: (target, record) => runtime.resolvePendingKakaoAdjacency(target, record && record.pageId),
    requestOcrForPayload: runtime.requestOcrForPayload,
    requestCanonicalTranslations: runtime.requestCanonicalTranslations,
    isAuthoritativePagePayload: payload => Boolean(payload && runtime.isDataUrl(payload.dataUrl)),
    findAdjacentPageTargets: runtime.findAdjacentKakaoPageTargets,
    resolvePageRecord: target => {
      return runtime.state.kakaoStore && typeof runtime.state.kakaoStore.getPageHandleForTarget === "function" ? runtime.state.kakaoStore.getPageHandleForTarget(target) : null;
    },
    buildSeamPayload: runtime.buildKakaoSeamPayload,
    detectAdjacentPixelRisk: runtime.detectAdjacentKakaoPixelRisk,
    getTargetForPageId: runtime.getTargetForKakaoPageId,
    renderCanonicalProjections: runtime.renderCanonicalProjections,
    clearCanonicalProjection: target => runtime.clearRenderedTarget(target),
    computeTargetKey: runtime.computeTargetKey,
    getQuickSourceToken: runtime.getQuickSourceToken,
    buildTargetSourceCacheKey: runtime.buildTargetSourceCacheKey,
    captureTargetSnapshot: runtime.captureTargetSnapshot,
    isTargetSnapshotStillValid: runtime.isTargetSnapshotStillValid,
    getTargetGeneration: runtime.getKakaoTargetGeneration,
    renderLoadingOverlay: runtime.renderLoadingOverlay,
    clearLoadingOverlay: runtime.clearKakaoLoadingOverlay,
    scheduleAutoTranslateRetry: runtime.scheduleAutoTranslateRetry,
    reportPipelineError: runtime.reportKakaoPipelineError,
    tracePipeline: runtime.tracePipeline,
    get targetLanguage() {
      return runtime.getTargetLanguage?.() || runtime.KAKAO_CANONICAL_TARGET_LANGUAGE;
    },
    get sourceLanguage() {
      return runtime.getConfiguredSourceLanguage?.() || runtime.KAKAO_CANONICAL_SOURCE_LANGUAGE;
    },
    edgeWaitTimeoutMs: 8000
  }) : null;
  runtime.kakaoCanonicalPipeline = kakaoCanonicalPipeline;
  const kakaoPipeline = runtime.kakaoCanonicalPipeline;
  runtime.kakaoPipeline = kakaoPipeline;
  const api = {
    invalidated: false,
    rescan: runtime.rescan,
    manualTranslateVisible: runtime.manualTranslateVisible,
    translateNovelChapter: runtime.translateNovelChapter,
    retryNovelImages: runtime.retryNovelImages,
    togglePageAutoTranslate: runtime.togglePageAutoTranslate,
    getPageAutoTranslateStatus: runtime.getPageAutoTranslateStatus,
    __test: {
      /** 访问 Store（已封装） */
      get kakaoStore() {
        return runtime.state.kakaoStore;
      },
      get kakaoPipeline() {
        return runtime.kakaoPipeline;
      },
      get kakaoCanonicalPipeline() {
        return runtime.kakaoCanonicalPipeline;
      },
      mapKakaoStitchedResult: runtime.mapKakaoStitchedResult,
      dedupeKakaoResultByPageCoordinates: runtime.dedupeKakaoResultByPageCoordinates,
      buildKakaoStitchWindowPlan: runtime.buildKakaoStitchWindowPlan,
      findKakaoStitchNeighborTarget: runtime.findKakaoStitchNeighborTarget,
      isVerifiedKakaoStitchNeighbor: runtime.isVerifiedKakaoStitchNeighbor,
      shouldFallbackFromKakaoStitch: runtime.shouldFallbackFromKakaoStitch,
      hasKakaoFragmentStructureRisk: runtime.hasKakaoFragmentStructureRisk,
      shouldRejectKakaoPageEdgeStitch: runtime.shouldRejectKakaoPageEdgeStitch,
      buildOcrRequestKey: runtime.buildOcrRequestKey,
      shouldUseKakaoCanonicalPipeline: runtime.shouldUseKakaoCanonicalPipeline,
      isKakaoEpisodeImageTarget: runtime.isKakaoEpisodeImageTarget,
      calculateKakaoSeamCaptureBandHeight: runtime.calculateKakaoSeamCaptureBandHeight,
      isMangaTranslatorOverlayTarget: runtime.isMangaTranslatorOverlayTarget,
      isSupportedTarget: runtime.isSupportedTarget,
      normalizeKakaoStableImageSource: runtime.normalizeKakaoStableImageSource,
      buildKakaoPageIdentity: runtime.buildKakaoPageIdentity,
      queuePendingKakaoAdjacency: runtime.queuePendingKakaoAdjacency,
      hasPendingKakaoAdjacency: runtime.hasPendingKakaoAdjacency,
      resolvePendingKakaoAdjacency: runtime.resolvePendingKakaoAdjacency,
      buildOcrMessageForPayload: runtime.buildOcrMessageForPayload,
      requestOcrForPayload: runtime.requestOcrForPayload,
      detachKakaoTargetForSourceChange: runtime.detachKakaoTargetForSourceChange,
      restoreKnownKakaoPageHandle: runtime.restoreKnownKakaoPageHandle,
      getTargetForKakaoPageId: runtime.getTargetForKakaoPageId,
      prepareKakaoTargetRevisionCheck: runtime.prepareKakaoTargetRevisionCheck,
      captureTargetSnapshot: runtime.captureTargetSnapshot,
      getCommittedEmbeddedOriginalSource: runtime.getCommittedEmbeddedOriginalSource,
      isTargetSnapshotStillValid: runtime.isTargetSnapshotStillValid,
      shouldReuseTargetInflight: runtime.shouldReuseTargetInflight,
      upgradeQueuedTranslationRequest: runtime.upgradeQueuedTranslationRequest,
      normalizeOcrObservationResult: runtime.normalizeOcrObservationResult,
      projectionToRendererBubble: runtime.projectionToRendererBubble,
      normalizeProjectionPages: runtime.normalizeProjectionPages,
      normalizeSeamRenderSurfaces: runtime.normalizeSeamRenderSurfaces,
      isValidCrossPageSegment: runtime.isValidCrossPageSegment,
      mapCompositeRectToCrossPageRoot: runtime.mapCompositeRectToCrossPageRoot,
      buildCrossPageBubbleGeometry: runtime.buildCrossPageBubbleGeometry,
      findCrossPageOverlayHost: runtime.findCrossPageOverlayHost,
      buildSeamSurfaceRenderSignature: runtime.buildSeamSurfaceRenderSignature,
      buildOverlayDebugRenderSignature: runtime.buildOverlayDebugRenderSignature,
      isSeamSurfaceRenderable: runtime.isSeamSurfaceRenderable,
      renderCrossPageSurfaces: runtime.renderCrossPageSurfaces,
      syncCrossPageOverlayGeometry: runtime.syncCrossPageOverlayGeometry,
      setSeamSourceModeForOverlays: runtime.setSeamSourceModeForOverlays,
      toggleSeamSourceMode: runtime.toggleSeamSourceMode,
      classifyCanonicalProjectionRender: runtime.classifyCanonicalProjectionRender,
      isCanonicalRenderComplete: runtime.isCanonicalRenderComplete,
      hasRenderableOcrDebug: runtime.hasRenderableOcrDebug,
      getRenderableOcrDebugStages: runtime.getRenderableOcrDebugStages,
      formatOcrDebugConfidence: runtime.formatOcrDebugConfidence,
      normalizeDebugCoordinateItems: runtime.normalizeDebugCoordinateItems,
      normalizePretranslateMode: runtime.normalizePretranslateMode,
      buildManualTranslateFeedback: runtime.buildManualTranslateFeedback,
      buildNovelProgressView: runtime.buildNovelProgressView,
      findKakaoNovelSurface: runtime.findKakaoNovelSurface,
      extractKakaoNovelChapter: runtime.extractKakaoNovelChapter,
      collectKakaoNovelImages: runtime.collectKakaoNovelImages,
      isNovelContentImage: runtime.isNovelContentImage,
      isNovelImageTarget: runtime.isNovelImageTarget,
      getNovelImageResultKey: runtime.getNovelImageResultKey,
      getRenderedNovelImageLines: runtime.getRenderedNovelImageLines,
      classifyNovelImageResult: runtime.classifyNovelImageResult,
      shouldOpenNovelImagePanel: runtime.shouldOpenNovelImagePanel,
      reapplyNovelEmbeddedImages: runtime.reapplyNovelEmbeddedImages,
      getEmbeddedTranslatedLines: runtime.getEmbeddedTranslatedLines,
      applyEmbeddedImageDataUrl: runtime.applyEmbeddedImageDataUrl,
      shouldUseEmbeddedRender: runtime.shouldUseEmbeddedRender,
      matchesTargetMarker: runtime.matchesTargetMarker,
      hasSettledTranslatedMarker: runtime.hasSettledTranslatedMarker,
      hasSettledNoTextMarker: runtime.hasSettledNoTextMarker,
      hasPendingTranslationMarkerState: runtime.hasPendingTranslationMarkerState,
      isTranslationRecoveryDue: runtime.isTranslationRecoveryDue,
      isReusableRenderedState: runtime.isReusableRenderedState,
      shouldPreserveOverlayDuringLoading: runtime.shouldPreserveOverlayDuringLoading,
      ensureLoadingStatusCard: runtime.ensureLoadingStatusCard,
      shouldKeepLoadingOverlayAfterTimeout: runtime.shouldKeepLoadingOverlayAfterTimeout,
      getLoadingOverlayRecoveryDiagnostic: runtime.getLoadingOverlayRecoveryDiagnostic,
      getLoadingOverlayCardPosition: runtime.getLoadingOverlayCardPosition,
      syncLoadingOverlayCardPosition: runtime.syncLoadingOverlayCardPosition,
      resolveCrossPageOriginalTextHeight: runtime.resolveCrossPageOriginalTextHeight,
      isReusableKakaoReadyPageBinding: runtime.isReusableKakaoReadyPageBinding,
      isCurrentKakaoPageBinding: runtime.isCurrentKakaoPageBinding,
      buildOverlayRenderSignature: runtime.buildOverlayRenderSignature,
      isSameOverlayRenderPayload: runtime.isSameOverlayRenderPayload,
      passesKakaoAheadTargetFilter: runtime.passesKakaoAheadTargetFilter,
      isAheadTranslationOptions: runtime.isAheadTranslationOptions,
      getTranslationQueueInsertIndex: runtime.getTranslationQueueInsertIndex,
      takeNextKakaoTranslationQueueItem: runtime.takeNextKakaoTranslationQueueItem,
      canStartKakaoTranslationQueueItem: runtime.canStartKakaoTranslationQueueItem,
      isKakaoReaderContentTarget: runtime.isKakaoReaderContentTarget,
      waitForPaint: runtime.waitForPaint,
      canStartQueuedTranslation: runtime.canStartQueuedTranslation,
      textSimilarity: runtime.textSimilarity,
      formatTranslationForOriginalLines: runtime.formatTranslationForOriginalLines,
      normalizeBubbleRotation: runtime.normalizeBubbleRotation,
      normalizeBubbleAlignment: runtime.normalizeBubbleAlignment,
      shouldUseVerticalJapaneseLayout: runtime.shouldUseVerticalJapaneseLayout,
      applyBubbleAnchorStyle: runtime.applyBubbleAnchorStyle,
      buildRegionClipPath: runtime.buildRegionClipPath,
      getBubbleRenderColors: runtime.getBubbleRenderColors,
      getDynamicStrokeWidth: runtime.getDynamicStrokeWidth,
      getCleanedPatchStyle: runtime.getCleanedPatchStyle,
      normalizeFillBox: runtime.normalizeFillBox,
      buildSolidBackgroundBox: runtime.buildSolidBackgroundBox,
      resolveBubbleCoverBox: runtime.resolveBubbleCoverBox,
      buildBubbleCoverProjection: runtime.buildBubbleCoverProjection,
      appendBubbleRenderLayers: runtime.appendBubbleRenderLayers,
      buildAheadTranslationOptions: runtime.buildAheadTranslationOptions,
      compareOverlayViewportRects: runtime.compareOverlayViewportRects,
      getOverlayPositionRect: runtime.getOverlayPositionRect,
      shouldHideOverlayRoot: runtime.shouldHideOverlayRoot,
      getOverlayVisibilityRect: runtime.getOverlayVisibilityRect,
      getVisibleViewportRect: runtime.getVisibleViewportRect,
      syncOverlayPosition: runtime.syncOverlayPosition,
      passesKakaopageTargetGeometry: runtime.passesKakaopageTargetGeometry,
      hasUsableKakaoStripCaptureRect: runtime.hasUsableKakaoStripCaptureRect,
      selectPendingAheadCandidates: runtime.selectPendingAheadCandidates,
      selectPendingContinuousCandidates: runtime.selectPendingContinuousCandidates,
      isAttachableKakaoShortPage: runtime.isAttachableKakaoShortPage,
      findKakaoVerticalOverlap: runtime.findKakaoVerticalOverlap,
      isAutomaticPretranslateMode: runtime.isAutomaticPretranslateMode,
      shouldSchedulePagePretranslation: runtime.shouldSchedulePagePretranslation,
      tracePipeline: runtime.tracePipeline,
      getPipelineTrace: () => globalThis.__MT_PIPELINE_TRACE__ || [],
      clearPipelineTrace: () => {
        globalThis.__MT_PIPELINE_TRACE__ = [];
      },
      findKakaoShortPageAttachmentOwner: runtime.findKakaoShortPageAttachmentOwner,
      normalizeKakaoStitchDebugCoordinates: runtime.normalizeKakaoStitchDebugCoordinates,
      maybeQueueKakaoShortPageAttachmentOwner: runtime.maybeQueueKakaoShortPageAttachmentOwner,
      maybeCropKakaoOverlappedPayload: runtime.maybeCropKakaoOverlappedPayload,
      sampleKakaoImageForOverlap: runtime.sampleKakaoImageForOverlap,
      normalizeKakaoStitchSegments: runtime.normalizeKakaoStitchSegments,
      getKakaoStitchOwnerOverlap: runtime.getKakaoStitchOwnerOverlap,
      getDebugItemPercentWithImageSize: runtime.getDebugItemPercentWithImageSize,
      mapKakaoStitchedFillBox: runtime.mapKakaoStitchedFillBox,
      mapKakaoStitchedPolygon: runtime.mapKakaoStitchedPolygon,
      buildTermDiscoveryMessage: runtime.buildTermDiscoveryMessage,
      buildNovelDiscoveryMessage: runtime.buildNovelDiscoveryMessage,
      releaseUncoveredKakaoShortPages: runtime.releaseUncoveredKakaoShortPages,
      releaseShortPagesAttachedDuringInflight: runtime.releaseShortPagesAttachedDuringInflight,
      hasAttachedShortPageBubble: runtime.hasAttachedShortPageBubble,
      buildKakaoStitchedPayload: runtime.buildKakaoStitchedPayload,
      findTargetByScopedKey: runtime.findTargetByScopedKey,
      setPipelineTraceEnabled: v => {
        runtime.ENABLE_PIPELINE_TRACE = v;
      }
    },
    destroy: runtime.destroy
  };
  runtime.api = api;

}
